###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: shop-service-weixin
#redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_weixin

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
###swagger相关配置
swagger:
  base-package: com.liudehuang.weixin
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 会员接口文档
  version: 1.1
  terms-of-service-url: www.liudehuang.com
  contact:
    name: 刘德煌
    email: 2969878315@qq.com



logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
    - appId: wxbcee8356d006f6ef #（一个公众号的appid）
      secret: 64d616dddc9d3b51e913e6d58cbf9c39 #（公众号的appsecret）
      token: liudehuang #（接口配置里的Token值）

ldh:
  weixin:
    registration:
      code:
        message: 您的注册码为:%s,请关注我的个人微信公众号
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!
