###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: shop-service-member
  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
  ###数据库相关连接
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ldh-shop-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
###swagger相关配置
swagger:
  base-package: com.liudehuang.member
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 会员接口文档
  version: 1.1
  terms-of-service-url: www.liudehuang.com
  contact:
    name: 刘德煌
    email: 2969878315@qq.com
#打印mybatis日志
logging:
  level:
#开发环境使用debug，生产环境使用info或error
    com.liudehuang.member.mapper: debug